### ISSUE TITLE
Function parsing

### ISSUE THREAD

**Issue by CU-Sam** [jsdoctypeparser/jsdoctypeparser#107]
Hi and thank you for your job !

The basic parsing of callback functions as you describe it is : 
function(type1, type2, ...): returnType
This format does not allow naming of different args. Could you support this type of format : 
function(var1:type1, var2:type2, ...): returnType
or the arrow function format
(var1:type1, var2:type2, ...) => returnType

As your project is used within ESLint this could be very usefull.
Thanks

**Comment by brettz9** [comment]
I think this should be merged into #50 .

**Comment by CU-Sam** [comment]
The typescript notation of arrow function could do the trick. I tried it on your live demo and it works. Maybe ESLint does not contains the last version of your project. I'll check that in my project.
Thanks for the answer.

**Comment by brettz9** [comment]
To my knowledge ESLint was never using `jsdoctypeparser`. They had their own parser `doctrine` which they have since deprecated along with their jsdoc rules in favor of [`eslint-plugin-jsdoc`](https://github.com/gajus/eslint-plugin-jsdoc)--which does use `jsdoctypeparser`.

**Comment by CU-Sam** [comment]
Yes you're right this is the plugin eslint-plugin-jsdoc that use it. I checked on my project and it enclose the last version of jsdoctypeparser (5.1.1). To my surprise, the arrow function format is active in my project and works fine. I didn't realise it because I wrongly use this format (I omitted the types behind this arguments).

** confused **

Sorry for this PEBKAC !! :D
Thanks
