### ISSUE TITLE
Dropping `=` prefix (optional type indicator)

### ISSUE THREAD

**Issue by brettz9** [jsdoctypeparser/jsdoctypeparser#121]
There is the `PrefixOptionalTypeExpr` which indicates as an example `=string` (while mentioning it is deprecated--the suffixed version is not), but I don't see this in catharsis or mention of it in Closure docs, so it seems that one should be dropped from `jsdoctypeparser` entirely now, unless TS is using it. (If TS is using it, we could still handle it in `check-syntax` in `eslint-plugin-jsdoc` for the other modes.)

**Comment by sandersn** [comment]
Nope, this is not supported in Typescript either.
