### ISSUE TITLE
Importing a type from another file appears to break

### ISSUE THREAD

**Issue by spacemonaut** [jsdoctypeparser/jsdoctypeparser#127]
This concerns **jsdoctypeparser version 9.0.0**.

A type defined with an import (like `import("./package").Type`) results in a syntax error being reported by `jsdoc/valid-types`. I provide a minimal reproducible example below. I also provide contents of my package-lock.json to affirm the version being used.

As far as I can tell, the import is written correctly and should work.

This relates to issue #50, and is similar to an issue previously raised on another repository (https://github.com/gajus/eslint-plugin-jsdoc/issues/343). [The bug report page at eslint-plugin-jsdoc](https://github.com/gajus/eslint-plugin-jsdoc/issues/new?assignees=&labels=bug-unconfirmed&template=bug_report.md&title=) says type parsing issues should be reported here, at time of writing under "Note 3" near the top.

# Minimal reproducible example

1. Create a new folder (in my case `jsdoc-test-app`) containing the three files found further down in this report: you should have `package.json`, `src/first.js`, and `src/second.js`. Note the package.json is using exact version numbers for its dependencies for the sake of reproducibility, you could feel free to add a `^` beforehand if you wish.
2. Run `npm install`
3. Run `npm run lint`

Expected: Everything is OK. This is a straightforward type import.

Actual: eslint reports an error originating from `jsdoc/valid-types`.

```
jsdoc-test-app/src/second.js
  1:0  warning  Syntax error in type: import("./first").Foo  jsdoc/valid-types

✖ 1 problem (0 errors, 1 warning)
```

# Files

## package.json

```json
{
  "name": "jsdoc-test-app",
  "private": true,
  "scripts": {
    "lint": "eslint src/**/*.js"
  },
  "dependencies": {
    "eslint": "7.6.0",
    "eslint-plugin-jsdoc": "30.2.1"
  },
  "eslintConfig": {
    "root": true,
    "parserOptions": {
      "ecmaVersion": 11,
      "sourceType": "module"
    },
    "rules": {
      "valid-jsdoc": "off"
    },
    "plugins": [
      "jsdoc"
    ],
    "extends": [
      "eslint:recommended",
      "plugin:jsdoc/recommended"
    ]
  }
}
```

## src/first.js

```js
/** @interface Foo */
```

## src/second.js

```js
/** @typedef {import("./first").Foo} FooBar */
```

# Package-lock information

My package-lock.json file reports the following entries for jsdoctypeparser.

1. As a referenced dependency:

    ```json
    "eslint-plugin-jsdoc": {
      "version": "30.2.1",
      "resolved": "https://registry.npmjs.org/eslint-plugin-jsdoc/-/eslint-plugin-jsdoc-30.2.1.tgz",
      "integrity": "sha512-9Nx+BKMBoCTDRIbVpMV4MYfw+lvfnfsWTWYX9vwRRZrkXBpZkKtE3dsFcG6MhF7N/vW1cwpjEnoAIAtn0+a6gw==",
      "requires": {
        "comment-parser": "^0.7.5",
        "debug": "^4.1.1",
        "jsdoctypeparser": "^9.0.0",
        "lodash": "^4.17.19",
        "regextras": "^0.7.1",
        "semver": "^7.3.2",
        "spdx-expression-parse": "^3.0.1"
      }
    },
    ```

2. As the actual locked package:

    ```json
    "jsdoctypeparser": {
      "version": "9.0.0",
      "resolved": "https://registry.npmjs.org/jsdoctypeparser/-/jsdoctypeparser-9.0.0.tgz",
      "integrity": "sha512-jrTA2jJIL6/DAEILBEh2/w9QxCuwmvNXIry39Ay/HVfhE3o2yVV0U44blYkqdHA/OKloJEqvJy0xU+GSdE2SIw=="
    },
    ```

**Comment by brettz9** [comment]
As per #343, you should not be using `valid-jsdoc`, a rule that is not part of `eslint-plugin-jsdoc` but is rather a part of ESLint itself (though deprecated in favor of `eslint-plugin-jsdoc` and apparently causing the issue in question). See https://github.com/gajus/eslint-plugin-jsdoc/wiki/Comparison-with-deprecated-JSdoc-related-ESLint-rules for the equivalents corresponding to `valid-jsdoc` which you can find within `eslint-plugin-jsdoc`.

After note that if you are using TypeScript features like `import()`, you will need to add `settings: {jsdoc: {mode: 'typescript'}}` to your ESLint config (or use the `@typescript/eslint-parser` parser for your `parser`).

Closing as that should resolve though feel free to comment further as needed.

**Comment by spacemonaut** [comment]
> As per #343, you should not be using `valid-jsdoc`

Noted. I have `"valid-jsdoc": "off"` in this example.

> After note that if you are using TypeScript features like `import()`, you will need to add `settings: {jsdoc: {mode: 'typescript'}}` to your ESLint config (or use the `@typescript/eslint-parser` parser for your `parser`).

Thank you. Adding that to the end of my eslintConfig worked. New package.json:
 
```js
{
  // ...
  "eslintConfig": {
    // ...
    "settings": {
      "jsdoc": {"mode": "typescript"}
    }
  }
}
```

**Comment by brettz9** [comment]
Great. Might be safer to just remove `valid-jsdoc` entirely, as it is not included with `eslint:recommended` (in case you were to ever add that and worry that it would include `valid-jsdoc` by default), and though ESLint doesn't seem to complain currently when a non-existent rule is disabled, I wouldn't want to run that risk myself.
