### ISSUE TITLE
Type {[user: Object, info: string]} not allowed with mode=typescript

### ISSUE THREAD

**Issue by thernstig** [jsdoctypeparser/jsdoctypeparser#135]
I have am using https://github.com/gajus/eslint-plugin-jsdoc/ with `settings.jsdoc.mode: "typescript"`.

An example where the returns statement does not work:

```js
/**
 * A promisified version of passport.authenticate to be used in async functions.
 *
 * @param {string} strategy - The strategy for the provider to use for the authentication flow
 * @param {express.Request} req - The Express request object
 * @param {express.Response} res - The Express request object
 * @param {Function} next - The next Express middleware function
 *
 * @returns {[user: Object, info: string]} The user and info
 */
```

This reports `Syntax error in type: [user: Object, info: string] eslintjsdoc/valid-types)`

**Comment by brettz9** [comment]
Closing as dupe. See labeled tuple types to-do in #50 .

**Comment by ExE-Boss** [comment]
Duplicate of <https://github.com/jsdoctypeparser/jsdoctypeparser/issues/50>

**Comment by thernstig** [comment]
Darnit, I searched in eslint-plugin-jsdoc but forgot to search here :(
