### ISSUE TITLE
Support for `...` as a suffix (JSDuck)

### ISSUE THREAD

**Issue by zxqfox** [jsdoctypeparser/jsdoctypeparser#32]
E.g.

```
String...
```

as

```
{
  "type": "VARIADIC",
  "value": {
    "type": "NAME",
    "name": "String"
  },
  "postfix": true
}
```

> - `{String...}` - variable number of string arguments.
> - `{String[]/Number[]...}` - variable number of string or number arrays.

Ref https://github.com/senchalabs/jsduck/wiki/Type-Definitions
Ref https://github.com/jscs-dev/jscs-jsdoc/issues/146

**Comment by Kuniwak** [comment]
This feature released with [v2.0.0-alpha-5](https://www.npmjs.com/package/jsdoctypeparser#variadic).
Please try it by [online demo](http://kuniwak.github.io/jsdoctypeparser/).

**Comment by zxqfox** [comment]
@Kuniwak 
Check this:
```
{...string/number}
{string/number...}
```

From JSDuck:
> `{String[]/Number[]...}` - variable number of string or number arrays.

So `...` applies to both. It's valid for the first case, but not in the second. Feels like a bug.

And also:
```
{string.../number}
```
Not sure that it is valid. ;-\

/cc @Krinkle

**Comment by zxqfox** [comment]
Big thanks for quick response! ;-)

**Comment by Kuniwak** [comment]
OK, I'm gonna fix it.

But the current implementation has a deep problem about operator precedence.
So this may take a while.

**Comment by zxqfox** [comment]
Yeah, I've expected this ;-( It's ok, I'm gonna try to implement the latest version info jscs-jsdoc at this weekend. But I guess this bug wont disturb.

**Comment by Kuniwak** [comment]
This feature was added on v2.0.0-alpha-6.
You can try it on http://kuniwak.github.io/jsdoctypeparser/ .
