### ISSUE TITLE
Allow quotation marks for "external:" and "module:" paths

### ISSUE THREAD

**Issue by brettz9** [jsdoctypeparser/jsdoctypeparser#58]
Per http://jsdoc.app/tags-external.html , external type paths should allow namespaces to be added via quotation marks: e.g., `external:"jQuery.fn".starfairy` may exist and this is expected in jsdoc3/jsdoc.

Per https://github.com/jsdoc/jsdoc/issues/490 , `@module` may also use quotes (even at the top level, though presumably one must use the optional "module:" prefix if inside of a type expression to avoid it being treated as a string).

In theory the top level of a regular namepath ought to allow for quoted forms as well (e.g., `"goofy.global".child.path`, possible through `window['goofy.global'] = {child: {path: ''}};`), no less if a type name with special characters wasn't even mapped to a variable, but since there would be ambiguity with strings if referencing the top level alone (and unlike `module:`, there is no prefix for regular name paths to avoid this ambiguity) and few global objects (or types) would tend to be named with non-`JsIdentifier` characters, I guess this is not of concern. Also, though properties would not *need* to be restricted as variable names, I see that jsdoc ruled it out because of the string ambiguity per https://github.com/jsdoc/jsdoc/issues/395#issuecomment-16245182 , so I guess we don't need to support quoted properties at the top level for regular name paths.

**Comment by brettz9** [comment]
@sandersn , I presume Typescript may have an issue with this as well?

**Comment by ExE-Boss** [comment]
TypeScript doesn’t support the&nbsp;`@external`&nbsp;tag.

**Comment by brettz9** [comment]
@ExE-Boss : Thanks, but per @sandersn , the only deliberate lack of support of JSDoc in TypeScript is with module paths, so I presume it is on the to-do list, along with the paths that will target that tag.

**Comment by sandersn** [comment]
Typescript might add support for `@external` as a means of introducing symbols without associated values, since it's very similar to our ambient declarations:

```ts
declare module "jquery" {
  declare namespace fn {
    declare function starfairy();
  }
}
```

but I don't think we will add support for `external:` references since that's part of a namepath. Support would probably look like a normal Typescript reference that relies on module resolution:

```ts
/** @type {import("jQuery.fn").starfairy} */
```

I don't remember seeing an bug for `@external` though; from a survey I took last year, most people reported knowing about (and using) d.ts files for declarations. So I suspect that method of declaring symbols has overshadowed the JSDoc way.

**Comment by brettz9** [comment]
Ok, I've referenced this at https://github.com/jsdoc3/jsdoc/issues/1632 . Hopefully we'll see some compatibility forthcoming somehow.

Btw, you might also see that issue regarding how I presume the `import` syntax must work given that jQuery doesn't actually export `fn` (and may not once it may follow ESM).

**Comment by brettz9** [comment]
I edited my original post to mention that `module:` should also support quotes, and a discussion of why we probably don't need to worry about supporting quoting of top-level name paths (mostly due to potential ambiguity with strings, even if some cases like say "goofy-global"."another-quoted" could remove the ambiguity).
