### ISSUE TITLE
Move GitHub Page to root

### ISSUE THREAD

**Issue by ExE-Boss** [jsdoctypeparser/jsdoctypeparser#73]
Since JSDocTypeParser is now in its own GitHub organisation, it might be a good idea to move the contents of the `gh‑pages` branch to https://github.com/jsdoctypeparser/JSDocTypeParser.GitHub.io.

Preferably by pushing the current `gh‑pages` branch as the `master` branch of https://github.com/jsdoctypeparser/JSDocTypeParser.GitHub.io.

I have currently pushed that as the `master-disabled` branch (this is because GitHub pages on the root page are deployed from the `master` branch).

To enable https://JSDocTypeParser.GitHub.io, the `master-disabled` branch will have to be renamed to `master`.

**Comment by brettz9** [comment]
Sounds fine by me... But should the casing be CamelCased in https://github.com/jsdoctypeparser/JSDocTypeParser.GitHub.io ?

**Comment by ExE-Boss** [comment]
The casing of the repository doesn’t matter, see also https://github.com/ExE-Boss/ExE-Boss.GitHub.io.

**Comment by brettz9** [comment]
@sandersn , are you ok with our just renaming `master-disabled` to `master` on https://jsdoctypeparser.github.io/ so we can get our demo on that repo and then delete the gh-pages branch?

**Comment by sandersn** [comment]
That sounds like a great idea to me. 

I didn't even think to look at github.io to see if jsdoctypeparser had documentation, so thanks for doing so.

**Comment by brettz9** [comment]
Ok, it's now enabled, links updated, and `gh-pages` deleted. Thanks!
