### ISSUE TITLE
Large size of published npm package

### ISSUE THREAD

**Issue by CheerlessCloud** [jsdoctypeparser/jsdoctypeparser#95]
Hi 👋
Npm package of this lib has a size around 9Mb because your fixtures from the tests directory automatically added to the published package. To prevent this behavior, you should explicitly define files property in package.json or create .npmignore file in the root directory ([documentation](https://docs.npmjs.com/files/package.json#files)).

I can send PR for this change if you want.

**Comment by brettz9** [comment]
Thanks for pointing this out.. Added to `master`!

**Comment by brettz9** [comment]
![image](https://user-images.githubusercontent.com/20234/66278201-4e41e780-e8d9-11e9-970b-e7876619ec0c.png)
